version: '3.7'

networks:
  monitoring:
  
services:
  opentelemetry-collector:
      image: otel/opentelemetry-collector:0.71.0
      restart: unless-stopped
      command: --config=/conf/otel-collector.config.yaml
      ports: ["9464:9464", "55680:55680", "55681:55681"]
      volumes:
        - ./otel-collector.yaml:/conf/otel-collector.config.yaml
        - ./out/:/opt/out/filename.json
      networks: [monitoring]